junit:
  stage: test
  script:
    - cd TractFitt mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - cd TractFitt mvn -B clean site package
  artifacts:
    paths:
      - target/s202*.jar